data_types = {
    "bigint",
    "bigserial",
    "bit",
    "bit varying",
    "boolean",
    "box",
    "bytea",
    "character",
    "character varying",
    "cidr",
    "circle",
    "date",
    "double precision",
    "inet",
    "integer",
    "interval",
    "json",
    "jsonb",
    "line",
    "lseg",
    "macaddr",
    "macaddr8",
    "money",
    "numeric",
    "path",
    "pg_lsn",
    "pg_snapshot",
    "point",
    "polygon",
    "real",
    "smallint",
    "smallserial",
    "text",
    "time," "time with time zone",
    "time without time zone",
    "timestamp",
    "timestamp with time zone",
    "timestamp without time zone",
    "tsquery",
    "tsvector",
    "txid_snapshot",
    "uuid",
    "xml",
}

constraints = {
    "not null",
    "unique",
    "primary key",
    "foreign key",
    "references",
    "check",
    "exclude using",
}

phrases = {
    "current_date",
    "current_time",
    "current_timestamp",
    "localtime",
    "localtimestamp",
    "LOCALTIME",
    "CURRENT_TIME",
    "CURRENT_DATE",
    "LOCALTIMESTAMP",
    "CURRENT_TIMESTAMP",
}
